// Regenerates src/abi/generated.ts from the Foundry build of ../contracts (run `forge build` first).
// Errors from every contract are merged into each ABI so viem can decode any bubbled-up revert.
import { readFileSync, writeFileSync } from 'node:fs'
const out = new URL('../../contracts/out/', import.meta.url)
const load = (file, name) => JSON.parse(readFileSync(new URL(`${file}/${name}.json`, out))).abi
const src = {
  factoryAbi: load('DmdSwapFactory.sol', 'DmdSwapFactory'),
  pairAbi: load('DmdSwapPair.sol', 'DmdSwapPair'),
  routerAbi: load('DmdSwapRouter.sol', 'DmdSwapRouter'),
  nameRouterAbi: load('DmdNameRouter.sol', 'DmdNameRouter'),
  nameResolverAbi: load('DmdNameResolver.sol', 'DmdNameResolver'),
  wdmdAbi: load('WDMD.sol', 'WDMD'),
  erc20Abi: load('ERC20.sol', 'ERC20'),
}
const sig = (e) => `${e.name}(${e.inputs.map((i) => i.type).join(',')})`
const allErrors = new Map()
for (const abi of Object.values(src)) for (const e of abi) if (e.type === 'error') allErrors.set(sig(e), e)
let ts = '// AUTO-GENERATED by scripts/sync-abi.mjs from the compiled DMDSwap contracts. Do not edit.\n\n'
for (const [name, abi] of Object.entries(src)) {
  const items = abi.filter((e) => e.type !== 'error' && e.type !== 'constructor')
  const merged = [...items, ...allErrors.values()]
  ts += `export const ${name} = ${JSON.stringify(merged)} as const\n\n`
}
writeFileSync(new URL('../src/abi/generated.ts', import.meta.url), ts)
console.log('wrote src/abi/generated.ts with', allErrors.size, 'shared error definitions')
